[window]
startup_mode = "Windowed"
dynamic_padding = true
opacity = 0.95
[window.padding]
x = 26
y = 26


[[hints.enabled]]
regex = "[^ ]+\\.rs:\\d+:\\d+"
command = { program = "code", args = [ "--goto" ] }
mouse = { enabled = true }

[font]
size = 11.0
[font.bold]
family = "Jetbrains Mono"
style = "Bold"

[font.bold_italic]
family = "monospace"
style = "Bold Italic"

[font.italic]
family = "monospace"
style = "Italic"

[font.normal]
family = "Jetbrains Mono"
style = "Regular"
